apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: aiprod-v33-api
  namespace: default
  annotations:
    run.googleapis.com/ingress: internal
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      serviceAccountName: aiprod-sa
      containers:
        - image: gcr.io/aiprod-484120/aiprod-v33:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: aiprod-db-url
                  key: url
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gemini-api-key
                  key: key
            - name: GOOGLE_CLOUD_PROJECT
              value: "aiprod-484120"
            - name: GCS_BUCKET_NAME
              value: "aiprod-v33-assets"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/secrets/google/key.json"
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
      volumes:
        - name: google-cloud-key
          secret:
            secretName: aiprod-sa-key
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: aiprod-v33-worker
  namespace: default
  annotations:
    run.googleapis.com/ingress: internal
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "5"
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/cpu-throttling: "false"
    spec:
      serviceAccountName: aiprod-sa
      containers:
        - image: gcr.io/aiprod-484120/aiprod-v33:latest
          command:
            - "python"
            - "-m"
            - "src.workers.pipeline_worker"
            - "--threads"
            - "5"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: aiprod-db-url
                  key: url
            - name: GOOGLE_CLOUD_PROJECT
              value: "aiprod-484120"
            - name: GCS_BUCKET_NAME
              value: "aiprod-v33-assets"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/secrets/google/key.json"
          resources:
            limits:
              cpu: "4"
              memory: "4Gi"
            requests:
              cpu: "2"
              memory: "2Gi"
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
      volumes:
        - name: google-cloud-key
          secret:
            secretName: aiprod-sa-key
