steps:
  # Step 1: Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    id: "build"
    args:
      - "build"
      - "-t"
      - "${_GCR_HOSTNAME}/${PROJECT_ID}/${_IMAGE_NAME}"
      - "-t"
      - "${_GCR_HOSTNAME}/${PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}"
      - "-f"
      - "Dockerfile"
      - "."

  # Step 2: Push to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    id: "push"
    args:
      - "push"
      - "${_GCR_HOSTNAME}/${PROJECT_ID}/${_IMAGE_NAME}"

  # Step 3: Deploy to Cloud Run (API Server)
  - name: "gcr.io/cloud-builders/gke-deploy"
    id: "deploy-api"
    args:
      - "run"
      - "--filename=."
      - "--image=${_GCR_HOSTNAME}/${PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}"
      - "--location=us-central1"
      - "--output=."
    env:
      - "CLOUDSDK_COMPUTE_REGION=us-central1"
      - "CLOUDSDK_CONTAINER_CLUSTER=aiprod-cluster"

  # Step 4: Run tests in Cloud Build
  - name: "${_GCR_HOSTNAME}/${PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}"
    id: "test"
    entrypoint: "/bin/bash"
    args:
      - "-c"
      - |
        pip install pytest pytest-cov
        pytest tests/unit/ -v --cov=src --cov-report=term

  # Step 5: Generate test report
  - name: "gcr.io/cloud-builders/docker"
    id: "test-report"
    args:
      - "run"
      - "--rm"
      - "${_GCR_HOSTNAME}/${PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}"
      - "python"
      - "-m"
      - "pytest"
      - "tests/unit/"
      - "--tb=short"
      - "--junit-xml=/workspace/test-results.xml"

images:
  - "${_GCR_HOSTNAME}/${PROJECT_ID}/${_IMAGE_NAME}"
  - "${_GCR_HOSTNAME}/${PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}"

substitutions:
  _GCR_HOSTNAME: "gcr.io"
  _IMAGE_NAME: "aiprod-v33"

options:
  machineType: "N1_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY
  substitution_option: "ALLOW_LOOSE"

timeout: "1800s"

artifacts:
  objects:
    location: "gs://${PROJECT_ID}-cloudbuild/test-results"
    paths:
      - "test-results.xml"
